name: "Cd for sample one"

on:
    workflow_run:
        workflows: ["CI for sample 1"]
        types:
            - completed
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: Production
        steps:
            - name: "Setup node js"
              uses: actions/setup-node@v4
              with:
                  node-version: '21'
            - name: "Check node version"
              run: node --version
            - name: "Install vercel CLI"
              run: npm install -g vercel
            - name: "Download build files"
              uses: actions/download-artifact@v4
              with:
                    name: build
                    run-id: ${{ github.event.workflow_run.id }}
                    github-token: ${{ secrets.GITHUB_TOKEN }}
            - name: "Deploy to vercel"
              run: vercel --prod --tokens=${{ secrets.VERCEL_TOKEN }} --confirm --name=sample1

                         