name: "CI for sample 1"

on: 
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "setup node js"
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: "Check node version"
        run: node --version
      - name: "Clone the repository"
        uses: actions/checkout@v2
      - name: 'Install dependencies'
        run: npm install
      - name: "Install plugins"
        run: npm install @rollup/plugin-image --save-dev
      - name: "Build the app"
        run: npm run build
      - name: "upload product-ready build files"
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
